name: 'Build and Deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd BenpaiBot
            git pull
            npm up
            pm2 restart 3
